#
# settings related to recompiling and reruning app when source changes
#
[hotreload]
  # file suffixes to watch for changes
  suffixes = [".go"]

  # files/directories to ignore
  ignore = []

#
# general application settings
#
[app]
  # additional application arguments
  args = []
  addr = ":3000"

  [app.logger]
    level = "DEBUG"
    name = "application"

##### 运行参数
[mysql]
  connect = "root:huabinglan@@227@(192.168.1.117:3306)/pizzaCms?charset=utf8&parseTime=True&loc=Local"
  MaxIdle = 10
  MaxOpen = 100
[mongodb]
  connect = "mongodb://192.168.1.117:10000/admin"
[redis]
  connect = "192.168.1.134:6379"
  db = 0
  maxidle = 100
  maxactive = 1000
#
# neo settings
#
[neo]
  [neo.logger]
  level = "INFO"
